---
name: Terraform
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  name: Terraform
  terraform:
    env: 
     ARM_SUBSCRIPTION_ID = ${{ secrets.AZURE_SUBSCRIPTION_ID }} 
     ARM_TENANT_ID = ${{ secrets.AZURE_TENANT_ID }} 
     ARM_CLIENT_ID = ${{ secrets.AZURE_CLIENT_ID }} 
     ARM_CLIENT_SECRET = ${{ secrets.AZURE_CLIENT_SECRET }}
    runs-on: ubuntu-latest
    environment: production
  defaults:
    run:
      shell: bash
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: |
        terraform plan -input=false -out=infra.tfplan 
    - name: Terraform Apply
      run: terraform apply -auto-approve infra.tfplan
